### PR TITLE
implements slightly more Rust-y error handling in main function

### PR DESCRIPTION
**Pull request by sts10**

### CODE REVIEW

**Comment by mttaggart** [comment]
Does `Err` from `main()` actually return a non-zero error code? It's important to me that the script operates as expected from the shell.

**Comment by sts10** [comment]
Great question. 

Upon investigating, I learned two things I didn't know before: 
1.) `echo $?` [prints your last command's exit code](https://www.redhat.com/sysadmin/exit-codes-demystified#:~:text=To%20display%20the%20exit%20code,%24%20echo%20%24%3F)
2.) I don't think `-1` is a valid exit code?

Armed with the knowledge that `echo $?` prints the last command's exit code, I did some experimentation. 

First, I made the assumption (I think correct) that to get the error we're debating, we're to give pwfuzz-rs a non-existent rules file. 

Here's how that goes on pwfuzz-rs's current `main` branch:
```text
$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
$ cargo run -- -r files/that/does/not/exit -w wordlist-that-does-exist.txt 
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/pwfuzz-rs -r files/that/does/not/exit -w wordlist-that-does-exist.txt`
EOF while parsing a value at line 1 column 0
$ echo $?
255
```

I see that currently, pwfuzz-rs tries to return an exit code of `-1`. Again, I don't think that's a valid exit code? Exit code 255 seems to the exit code given when ["Exit status is out of range"](https://tldp.org/LDP/abs/html/exitcodes.html). Maybe not what we want.

Here's how my PR handles the same test:

```text
$ git checkout better_error_handling 
Switched to branch 'better_error_handling'
$ cargo run -- -r files/that/does/not/exit -w wordlist-that-does-exist.txt
   Compiling pwfuzz-rs v0.1.2 (/home/sschlinkert/code/pwfuzz-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 0.80s
     Running `target/debug/pwfuzz-rs -r files/that/does/not/exit -w wordlist-that-does-exist.txt`
Error: "EOF while parsing a value at line 1 column 0"
$ echo $?
1
```

First of all, as per your question, we can see it's a non-zero exit code. Phew.

In fact, it seems like an exit code of 1 is preferable to 255. Exit code 1 apparently means "impermissible operations" or ["Catchall for general errors"](https://tldp.org/LDP/abs/html/exitcodes.html). 

And if you run `cd directory-that-does-not-exist`, which seems like a similar-ish problem, you get an exit code of 1.

**Comment by sts10** [comment]
(Whether `Error: "EOF while parsing a value at line 1 column 0"` is a helpful error message for a file not existing is a different question...)

**Comment by mttaggart** [comment]
Okay! Well TIL.

Also, in my own digging, I was considering [`ExitCode`](https://doc.rust-lang.org/std/process/struct.ExitCode.html) as an alternative. 

But there's some useful info here on [`ExitCode::FAILURE`](https://doc.rust-lang.org/std/process/struct.ExitCode.html#associatedconstant.FAILURE):

> The canonical ExitCode for unsuccessful termination on this platform.
>
> If you’re only returning this and SUCCESS from main, consider instead returning Err(_) and Ok(()) respectively, which will return the same codes (but will also eprintln! the error).

So I guess that's the move.

**Comment by sts10** [comment]
Yeah, I kind of figured this was a case of "trust the Rust folks to have `Err()` do what you want."

**Pull request merged**
